FIND_PATH(DYNAMIND_INCLUDE_DIR dmmodule.h  PATH_SUFFIXES dynamindcore)
FIND_LIBRARY(DYNAMINDTOOLBOX_LIBRARY NAMES dynamindtoolbox )
FIND_LIBRARY(DYNAMINDCORE_LIBRARY NAMES dynamindcore )

IF( DYNAMIND_INCLUDE_DIR AND DYNAMINDCORE_LIBRARY AND DYNAMINDTOOLBOX_LIBRARY )
   SET(DYNAMIND_FOUND TRUE)
ENDIF()

IF(DYNAMIND_FOUND)
    MESSAGE(STATUS "Found DynaMind core: ${DYNAMINDCORE_LIBRARY}")
    MESSAGE(STATUS "Found DynaMind toolbox: ${DYNAMINDTOOLBOX_LIBRARY}")
ELSE()
    MESSAGE(FATAL_ERROR "Could not find Dynamind libraries")
ENDIF()
