#!/bin/bash

## cleanup

rm html/*
rm latex/*
rm pdf/*

## compile

for i in `ls markdown/*.md`
do
	filename=$(basename $i)
	filename="${filename%.*}"
	kramdown -o html $i > html/$filename.html
	kramdown -o latex --template 'dynalp.erb' $i > latex/$filename.tex
	pdflatex -output-directory=pdf latex/$filename.tex > /dev/null 2>&1
done

## pdftex cleanup

find pdf/ -type f ! -iname '*.pdf' -delete

## deploy

rsync -a html latex pdf c8451116@dynalp.com:~/dynalp.com/documentation/DynaMind/
