Document: vibe2core
Title: Debian vibe2core Manual
Author: <insert document author here>
Abstract: This manual describes what vibe2core is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/vibe2core/vibe2core.sgml.gz

Format: postscript
Files: /usr/share/doc/vibe2core/vibe2core.ps.gz

Format: text
Files: /usr/share/doc/vibe2core/vibe2core.text.gz

Format: HTML
Index: /usr/share/doc/vibe2core/html/index.html
Files: /usr/share/doc/vibe2core/html/*.html
